---
root: true
extends:
  - '@epaew/eslint-config/react-typescript'
  - 'prettier'
plugins:
  - '@typescript-eslint'
rules:
  '@typescript-eslint/no-empty-function': off
overrides:
  - files:
      - '*.tsx'
    plugins:
      - react
    rules:
      react/jsx-uses-react: off
      react/react-in-jsx-scope: off
  - files:
      - jest.config.js
    env:
      node: true
  - files:
      - '__mocks__/*'
      - '*.test.ts{,x}'
    plugins:
      - '@typescript-eslint'
      - react
    rules:
      '@typescript-eslint/no-explicit-any': off
      react/prop-types: off
