name: Deploy example app to gh-pages

on:
  # pull_request: {}
  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  build:
    name: Build react-liff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 14.x
          cache: yarn

      - run: yarn install --frozen-lockfile
      - run: yarn run build
      - name: Upload the result of build react-liff
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  build-example-app:
    name: Build example app
    runs-on: ubuntu-latest
    needs:
      - build
    defaults:
      run:
        working-directory: examples/simple
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: 14.x
          cache: yarn
      - name: Download the result of build react-liff
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - run: yarn install
      - run: yarn run build
        env:
          REACT_APP_LINE_LIFF_ID: ${{ secrets.LINE_LIFF_ID }}
          NODE_ENV: production
          PUBLIC_URL: /react-liff
      - name: Upload the result of build react-liff
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: examples/simple/build

  deploy:
    name: Deploy to gh-pages
    runs-on: ubuntu-latest
    needs:
      - build-example-app
    steps:
      - name: Download the result of build react-liff
        uses: actions/download-artifact@v2
        with:
          name: build
          path: examples/simple/build
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          cname: www.epaew.net
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./examples/simple/build
